//! `cplt init` subcommand — auto-generate .cplt.toml from project detection.
//!
//! Scans the current project for build files, frameworks, and patterns,
//! then generates a .cplt.toml file with appropriate sandbox permissions.

use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::Path;

use crate::detect::{Detection, DetectionReport, SandboxFlag, Suggestion};

/// Options for the init command (mapped from CLI args).
pub struct InitOptions {
    /// Write the generated config to disk.
    pub write: bool,
    /// Overwrite existing .cplt.toml (requires write).
    pub force: bool,
    /// Output only the TOML (no decoration/ecosystem info).
    pub quiet: bool,
}

/// Result of running the init command.
pub enum InitResult {
    /// Generated config (preview or written).
    Generated {
        toml: String,
        path: std::path::PathBuf,
        written: bool,
    },
    /// File already exists and --force not given.
    AlreadyExists(std::path::PathBuf),
    /// Nothing detected — empty project.
    NothingDetected,
    /// Write failed.
    WriteFailed(std::path::PathBuf, std::io::Error),
}

/// Run the init command from a pre-computed detection report.
/// Avoids redundant filesystem scans when the caller already has the report.
pub fn run_init(project_dir: &Path, report: &DetectionReport, opts: &InitOptions) -> InitResult {
    if report.detections.is_empty() {
        return InitResult::NothingDetected;
    }

    let toml = generate_toml(report);
    let config_path = project_dir.join(".cplt.toml");

    if opts.write {
        if config_path.exists() && !opts.force {
            return InitResult::AlreadyExists(config_path);
        }
        if let Err(e) = std::fs::write(&config_path, &toml) {
            return InitResult::WriteFailed(config_path, e);
        }
        return InitResult::Generated {
            toml,
            path: config_path,
            written: true,
        };
    }

    InitResult::Generated {
        toml,
        path: config_path,
        written: false,
    }
}

/// Format the detection report for human-readable stdout display.
pub fn format_report(report: &DetectionReport) -> String {
    let mut out = String::new();

    writeln!(out, "Detected ecosystems:").unwrap();
    writeln!(out).unwrap();

    for detection in &report.detections {
        write_detection(&mut out, detection);
    }

    if !report.diagnostics.is_empty() {
        writeln!(out, "Diagnostics:").unwrap();
        for diag in &report.diagnostics {
            writeln!(out, "  [{}/warning] {}", diag.detector, diag.message).unwrap();
        }
        writeln!(out).unwrap();
    }

    out
}

fn write_detection(out: &mut String, d: &Detection) {
    writeln!(out, "  • {}", d.name).unwrap();
    for signal in &d.signals {
        writeln!(out, "    ↳ {signal}").unwrap();
    }
    if !d.suggestions.is_empty() {
        writeln!(out, "    Suggests:").unwrap();
        for suggestion in &d.suggestions {
            writeln!(out, "      {}", format_suggestion(suggestion)).unwrap();
        }
    }
    writeln!(out).unwrap();
}

fn format_suggestion(s: &Suggestion) -> String {
    match s {
        Suggestion::Propose(flag) => format!("{} = true", flag.key_name()),
        Suggestion::AllowRead(p) => format!("allow.read += [\"{p}\"]"),
        Suggestion::AllowWrite(p) => format!("allow.write += [\"{p}\"]"),
        Suggestion::AllowPort(p) => format!("allow.ports += [{p}]"),
        Suggestion::AllowLocalhost(p) => format!("allow.localhost += [{p}]"),
        Suggestion::AllowCacheExec(p) => format!("allow.cache_exec += [\"{p}\"]"),
        Suggestion::DenyEnv(v) => format!("deny.env += [\"{v}\"]"),
        Suggestion::DenyPath(p) => format!("deny.paths += [\"{p}\"]"),
        Suggestion::AllowPrivateDomain(d) => {
            format!("proxy.allow_private_domains += [\"{d}\"]")
        }
    }
}

/// Generate a valid .cplt.toml from a detection report.
///
/// Only includes suggestions appropriate for repo-level config.
/// Machine-specific suggestions (cache_exec, home-relative paths) are emitted
/// as comments with guidance to add them to personal config.
pub fn generate_toml(report: &DetectionReport) -> String {
    let mut out = String::new();

    writeln!(out, "# Generated by `cplt init` — review before trusting.").unwrap();
    writeln!(
        out,
        "# Detected: {}",
        report
            .detections
            .iter()
            .map(|d| d.name)
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
    writeln!(out).unwrap();

    // Partition suggestions into repo-appropriate vs personal-config
    let mut deny_env: BTreeSet<&str> = BTreeSet::new();
    let mut deny_paths: BTreeSet<&str> = BTreeSet::new();
    let mut propose_flags: BTreeSet<&str> = BTreeSet::new();
    let mut allow_read: BTreeSet<&str> = BTreeSet::new();
    let mut allow_write: BTreeSet<&str> = BTreeSet::new();
    let mut allow_ports: BTreeSet<u16> = BTreeSet::new();
    let mut allow_localhost: BTreeSet<u16> = BTreeSet::new();
    let mut proxy_private: BTreeSet<&str> = BTreeSet::new();

    // Machine-specific suggestions → emitted as comments
    let mut personal_hints: Vec<String> = Vec::new();

    for s in &report.suggestions {
        match s {
            Suggestion::Propose(flag) => {
                propose_flags.insert(flag.key_name());
            }
            Suggestion::AllowRead(p) => {
                if is_home_relative(p) {
                    personal_hints.push(format!("sandbox.read += [\"{p}\"]  # in personal config"));
                } else {
                    allow_read.insert(p.as_str());
                }
            }
            Suggestion::AllowWrite(p) => {
                if is_home_relative(p) {
                    personal_hints
                        .push(format!("sandbox.write += [\"{p}\"]  # in personal config"));
                } else {
                    allow_write.insert(p.as_str());
                }
            }
            Suggestion::AllowPort(p) => {
                allow_ports.insert(*p);
            }
            Suggestion::AllowLocalhost(p) => {
                allow_localhost.insert(*p);
            }
            Suggestion::AllowCacheExec(p) => {
                personal_hints.push(format!(
                    "sandbox.allow_cache_exec += [\"{p}\"]  # in personal config"
                ));
            }
            Suggestion::DenyEnv(v) => {
                deny_env.insert(v.as_str());
            }
            Suggestion::DenyPath(p) => {
                deny_paths.insert(p.as_str());
            }
            Suggestion::AllowPrivateDomain(d) => {
                proxy_private.insert(d.as_str());
            }
        }
    }

    // [deny] section — unconditionally applied (tightening)
    let has_deny = !deny_env.is_empty() || !deny_paths.is_empty();
    if has_deny {
        writeln!(out, "[deny]").unwrap();
        if !deny_env.is_empty() {
            write_string_array(&mut out, "env", &deny_env);
        }
        if !deny_paths.is_empty() {
            write_string_array(&mut out, "paths", &deny_paths);
        }
        writeln!(out).unwrap();
    }

    // [propose] section — requires trust acceptance (relaxing)
    let has_propose = !propose_flags.is_empty()
        || !allow_read.is_empty()
        || !allow_write.is_empty()
        || !allow_ports.is_empty()
        || !allow_localhost.is_empty()
        || !proxy_private.is_empty();

    if has_propose {
        writeln!(out, "[propose]").unwrap();
        for flag in &propose_flags {
            // Look up the SandboxFlag to check for risk warnings
            let warning = SandboxFlag::iter_all()
                .find(|f| f.key_name() == *flag)
                .and_then(SandboxFlag::risk_warning);
            if let Some(warning) = warning {
                writeln!(out, "# ⚠️  {warning}").unwrap();
            }
            writeln!(out, "{flag} = true").unwrap();
        }
        if !propose_flags.is_empty() {
            writeln!(out).unwrap();
        }

        // [propose.allow] sub-section for arrays
        let has_allow = !allow_read.is_empty()
            || !allow_write.is_empty()
            || !allow_ports.is_empty()
            || !allow_localhost.is_empty();

        if has_allow {
            writeln!(out, "[propose.allow]").unwrap();
            if !allow_read.is_empty() {
                write_string_array(&mut out, "read", &allow_read);
            }
            if !allow_write.is_empty() {
                write_string_array(&mut out, "write", &allow_write);
            }
            if !allow_ports.is_empty() {
                write_port_array(&mut out, "ports", &allow_ports);
            }
            if !allow_localhost.is_empty() {
                write_port_array(&mut out, "localhost", &allow_localhost);
            }
            writeln!(out).unwrap();
        }

        // [propose.proxy] sub-section
        if !proxy_private.is_empty() {
            writeln!(out, "[propose.proxy]").unwrap();
            write_string_array(&mut out, "allow_private_domains", &proxy_private);
            writeln!(out).unwrap();
        }
    }

    // Personal config hints (machine-specific settings)
    if !personal_hints.is_empty() {
        writeln!(
            out,
            "# The following are machine-specific — add to ~/.config/cplt/config.toml:"
        )
        .unwrap();
        for hint in &personal_hints {
            writeln!(out, "# {hint}").unwrap();
        }
        writeln!(out).unwrap();
    }

    out
}

/// Check if a path starts with ~ (home-relative, not appropriate for repo config).
fn is_home_relative(path: &str) -> bool {
    path.starts_with('~')
}

/// Escape a string for use in TOML basic strings (double-quoted).
/// Prevents injection of arbitrary TOML via crafted file content.
fn toml_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

fn write_string_array(out: &mut String, key: &str, values: &BTreeSet<&str>) {
    if values.len() == 1 {
        writeln!(
            out,
            "{key} = [\"{}\"]",
            toml_escape(values.iter().next().unwrap())
        )
        .unwrap();
    } else {
        writeln!(out, "{key} = [").unwrap();
        for val in values {
            writeln!(out, "  \"{}\",", toml_escape(val)).unwrap();
        }
        writeln!(out, "]").unwrap();
    }
}

fn write_port_array(out: &mut String, key: &str, values: &BTreeSet<u16>) {
    let ports: Vec<String> = values.iter().map(ToString::to_string).collect();
    writeln!(out, "{key} = [{}]", ports.join(", ")).unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::detect::{SandboxFlag, Signal, Suggestion};

    #[test]
    fn generates_propose_flags() {
        let report = DetectionReport {
            detections: vec![Detection {
                name: "Docker",
                signals: vec![Signal::FileExists {
                    path: "Dockerfile".to_string(),
                }],
                suggestions: vec![Suggestion::Propose(SandboxFlag::AllowDocker)],
            }],
            suggestions: [Suggestion::Propose(SandboxFlag::AllowDocker)]
                .into_iter()
                .collect(),
            diagnostics: vec![],
        };

        let toml = generate_toml(&report);
        assert!(toml.contains("[propose]"));
        assert!(toml.contains("allow_docker = true"));
    }

    #[test]
    fn generates_deny_env() {
        let report = DetectionReport {
            detections: vec![Detection {
                name: "Environment secrets",
                signals: vec![],
                suggestions: vec![Suggestion::DenyEnv("API_SECRET_KEY".to_string())],
            }],
            suggestions: [Suggestion::DenyEnv("API_SECRET_KEY".to_string())]
                .into_iter()
                .collect(),
            diagnostics: vec![],
        };

        let toml = generate_toml(&report);
        assert!(toml.contains("[deny]"));
        assert!(toml.contains("API_SECRET_KEY"));
    }

    #[test]
    fn generates_allow_arrays() {
        let report = DetectionReport {
            detections: vec![Detection {
                name: "JVM (Gradle)",
                signals: vec![],
                suggestions: vec![
                    Suggestion::Propose(SandboxFlag::AllowJvmAttach),
                    Suggestion::AllowRead("~/.gradle/gradle.properties".to_string()),
                ],
            }],
            suggestions: [
                Suggestion::Propose(SandboxFlag::AllowJvmAttach),
                Suggestion::AllowRead("~/.gradle/gradle.properties".to_string()),
            ]
            .into_iter()
            .collect(),
            diagnostics: vec![],
        };

        let toml = generate_toml(&report);
        // Home-relative paths go to personal config hints (comments)
        assert!(!toml.contains("[propose.allow]"));
        assert!(toml.contains("~/.gradle/gradle.properties"));
        assert!(toml.contains("# in personal config"));
        assert!(toml.contains("allow_jvm_attach = true"));
    }

    #[test]
    fn generates_port_arrays() {
        let report = DetectionReport {
            detections: vec![Detection {
                name: "Docker",
                signals: vec![],
                suggestions: vec![
                    Suggestion::AllowPort(5432),
                    Suggestion::AllowPort(8080),
                    Suggestion::AllowLocalhost(3000),
                ],
            }],
            suggestions: [
                Suggestion::AllowPort(5432),
                Suggestion::AllowPort(8080),
                Suggestion::AllowLocalhost(3000),
            ]
            .into_iter()
            .collect(),
            diagnostics: vec![],
        };

        let toml = generate_toml(&report);
        assert!(toml.contains("ports = [5432, 8080]"));
        assert!(toml.contains("localhost = [3000]"));
    }

    #[test]
    fn multi_ecosystem_generates_merged_toml() {
        let report = DetectionReport {
            detections: vec![
                Detection {
                    name: "JVM (Gradle)",
                    signals: vec![],
                    suggestions: vec![Suggestion::Propose(SandboxFlag::AllowJvmAttach)],
                },
                Detection {
                    name: "Docker",
                    signals: vec![],
                    suggestions: vec![
                        Suggestion::Propose(SandboxFlag::AllowDocker),
                        Suggestion::AllowPort(5432),
                    ],
                },
            ],
            suggestions: [
                Suggestion::Propose(SandboxFlag::AllowJvmAttach),
                Suggestion::Propose(SandboxFlag::AllowDocker),
                Suggestion::AllowPort(5432),
            ]
            .into_iter()
            .collect(),
            diagnostics: vec![],
        };

        let toml = generate_toml(&report);
        assert!(toml.contains("allow_docker = true"));
        assert!(toml.contains("allow_jvm_attach = true"));
        assert!(toml.contains("ports = [5432]"));
        // Header should mention both
        assert!(toml.contains("JVM (Gradle)"));
        assert!(toml.contains("Docker"));
    }

    #[test]
    fn empty_report_minimal_output() {
        let report = DetectionReport {
            detections: vec![Detection {
                name: "Rust",
                signals: vec![],
                suggestions: vec![],
            }],
            suggestions: BTreeSet::new(),
            diagnostics: vec![],
        };

        let toml = generate_toml(&report);
        // Should just have the header comment and nothing else
        assert!(toml.contains("# Generated by"));
        assert!(!toml.contains("[deny]"));
        assert!(!toml.contains("[propose]"));
    }

    #[test]
    fn init_nothing_detected_on_empty_dir() {
        let dir = tempfile::tempdir().unwrap();
        let report = crate::detect::detect_project(dir.path());
        let result = run_init(
            dir.path(),
            &report,
            &InitOptions {
                write: false,
                force: false,
                quiet: false,
            },
        );
        assert!(matches!(result, InitResult::NothingDetected));
    }

    #[test]
    fn init_generates_preview() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("Cargo.toml"), "[package]\nname=\"x\"").unwrap();
        let report = crate::detect::detect_project(dir.path());
        let result = run_init(
            dir.path(),
            &report,
            &InitOptions {
                write: false,
                force: false,
                quiet: false,
            },
        );
        match result {
            InitResult::Generated { written, .. } => assert!(!written),
            _ => panic!("expected Generated"),
        }
    }

    #[test]
    fn init_writes_file() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("Dockerfile"), "FROM node:20").unwrap();
        let report = crate::detect::detect_project(dir.path());
        let result = run_init(
            dir.path(),
            &report,
            &InitOptions {
                write: true,
                force: false,
                quiet: false,
            },
        );
        match result {
            InitResult::Generated { written, path, .. } => {
                assert!(written);
                assert!(path.exists());
                let content = std::fs::read_to_string(&path).unwrap();
                assert!(content.contains("allow_docker"));
            }
            _ => panic!("expected Generated"),
        }
    }

    #[test]
    fn init_refuses_overwrite_without_force() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("Dockerfile"), "FROM node:20").unwrap();
        std::fs::write(dir.path().join(".cplt.toml"), "# existing").unwrap();
        let report = crate::detect::detect_project(dir.path());
        let result = run_init(
            dir.path(),
            &report,
            &InitOptions {
                write: true,
                force: false,
                quiet: false,
            },
        );
        assert!(matches!(result, InitResult::AlreadyExists(_)));
    }

    #[test]
    fn init_overwrites_with_force() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("Dockerfile"), "FROM node:20").unwrap();
        std::fs::write(dir.path().join(".cplt.toml"), "# existing").unwrap();
        let report = crate::detect::detect_project(dir.path());
        let result = run_init(
            dir.path(),
            &report,
            &InitOptions {
                write: true,
                force: true,
                quiet: false,
            },
        );
        assert!(matches!(
            result,
            InitResult::Generated { written: true, .. }
        ));
    }

    #[test]
    fn format_report_includes_ecosystems() {
        let report = DetectionReport {
            detections: vec![Detection {
                name: "Node.js",
                signals: vec![Signal::FileExists {
                    path: "package.json".to_string(),
                }],
                suggestions: vec![Suggestion::Propose(SandboxFlag::AllowLocalhostAny)],
            }],
            suggestions: [Suggestion::Propose(SandboxFlag::AllowLocalhostAny)]
                .into_iter()
                .collect(),
            diagnostics: vec![],
        };

        let text = format_report(&report);
        assert!(text.contains("Node.js"));
        assert!(text.contains("package.json"));
        assert!(text.contains("allow_localhost_any"));
    }

    #[test]
    fn cache_exec_goes_to_personal_hint() {
        let report = DetectionReport {
            detections: vec![Detection {
                name: "Playwright",
                signals: vec![],
                suggestions: vec![Suggestion::AllowCacheExec("ms-playwright".to_string())],
            }],
            suggestions: [Suggestion::AllowCacheExec("ms-playwright".to_string())]
                .into_iter()
                .collect(),
            diagnostics: vec![],
        };

        let toml = generate_toml(&report);
        // Should NOT be in [propose.allow] as a real key
        assert!(!toml.contains("[propose.allow]"));
        // Should be in personal config hint comment
        assert!(toml.contains("# sandbox.allow_cache_exec"));
        assert!(toml.contains("ms-playwright"));
        assert!(toml.contains("personal config"));
    }

    #[test]
    fn generated_toml_parses_as_valid_repo_config() {
        // Roundtrip: generate TOML → parse with repo_config deserializer
        let report = DetectionReport {
            detections: vec![
                Detection {
                    name: "Docker",
                    signals: vec![],
                    suggestions: vec![
                        Suggestion::Propose(SandboxFlag::AllowDocker),
                        Suggestion::AllowPort(5432),
                        Suggestion::AllowLocalhost(3000),
                    ],
                },
                Detection {
                    name: "Environment secrets",
                    signals: vec![],
                    suggestions: vec![Suggestion::DenyEnv("SECRET_KEY".to_string())],
                },
            ],
            suggestions: [
                Suggestion::Propose(SandboxFlag::AllowDocker),
                Suggestion::AllowPort(5432),
                Suggestion::AllowLocalhost(3000),
                Suggestion::DenyEnv("SECRET_KEY".to_string()),
            ]
            .into_iter()
            .collect(),
            diagnostics: vec![],
        };

        let toml_str = generate_toml(&report);
        // Should parse without error
        let parsed: crate::repo_config::RepoConfig =
            toml::from_str(&toml_str).expect("generated TOML should parse as valid RepoConfig");

        assert_eq!(parsed.propose.allow_docker, Some(true));
        assert_eq!(parsed.propose.allow.ports, vec![5432]);
        assert_eq!(parsed.propose.allow.localhost, vec![3000]);
        assert_eq!(parsed.deny.env, vec!["SECRET_KEY"]);
    }
}
