use std::fmt::Write;
use std::path::{Path, PathBuf};

use super::policy::{
    DENIED_CACHE_PREFIXES, DENIED_DOTFILES, DENIED_FILES, GPG_SIGNING_ALLOW_FILES, HOME_TOOL_DIRS,
    HomeToolDir, SENSITIVE_PROJECT_PATTERNS, SYSTEM_READ_FILES, TOOL_READ_DIRS,
};

/// Options for generating an SBPL sandbox profile.
///
/// All paths are validated for SBPL injection before interpolation.
pub struct ProfileOptions<'a> {
    pub project_dir: &'a Path,
    pub home_dir: &'a Path,
    pub extra_read: &'a [PathBuf],
    pub extra_write: &'a [PathBuf],
    pub extra_deny: &'a [PathBuf],
    /// If `Some`, only include these home tool dirs (tighter profile via discovery).
    /// If `None`, all known home tool dirs are included.
    pub existing_home_tool_dirs: Option<&'a [String]>,
    pub extra_ports: &'a [u16],
    pub localhost_ports: &'a [u16],
    pub proxy_port: Option<u16>,
    /// Allow reading .env files and private keys in the project dir.
    pub allow_env_files: bool,
    /// Allow outbound TCP to localhost on all ports.
    pub allow_localhost_any: bool,
    /// Per-session scratch directory with write+exec permissions.
    /// Used to redirect TMPDIR so tools can compile-then-execute.
    pub scratch_dir: Option<&'a Path>,
    /// Remove temp dir exec denies (break-glass for system TMPDIR exec).
    pub allow_tmp_exec: bool,
    /// Copilot CLI package directory (resolved from the binary location).
    /// Needed when Copilot is installed in a non-standard location (e.g. ~/n/
    /// via the `n` Node version manager) that isn't covered by TOOL_READ_DIRS.
    pub copilot_install_dir: Option<&'a Path>,
    /// Global git hooks directory from `core.hooksPath`.
    /// Git needs to read and execute hooks from this directory for commits.
    pub git_hooks_path: Option<&'a Path>,
    /// Allow GPG commit/tag signing. When true, grants read-only access to
    /// the public keyring and GPG agent socket. Private keys stay denied.
    pub allow_gpg_signing: bool,
}

/// Generate a complete SBPL sandbox profile from the given options.
///
/// Sections are emitted in a fixed order — SBPL uses last-match-wins semantics,
/// so deny rules must come after their corresponding allows. Each `emit_*` helper
/// writes a contiguous block; their call order must not be changed.
pub fn generate_profile(opts: &ProfileOptions) -> String {
    let mut sb = String::with_capacity(4096);
    let home = opts.home_dir.to_string_lossy();
    let project = opts.project_dir.to_string_lossy();

    emit_header(&mut sb, &project);
    emit_process_rules(&mut sb);
    emit_project_access(&mut sb, &project, opts.allow_env_files);
    emit_home_access(&mut sb, &home);
    emit_git_hooks(&mut sb, opts.git_hooks_path);
    emit_system_access(&mut sb, &home);
    emit_tool_dirs(&mut sb, &home, opts.existing_home_tool_dirs);
    emit_copilot_install(&mut sb, opts.copilot_install_dir);
    emit_system_files(&mut sb);
    emit_temp_rules(&mut sb, opts.allow_tmp_exec, opts.scratch_dir);
    emit_user_allows(&mut sb, opts.extra_read, opts.extra_write);
    emit_deny_rules(&mut sb, &home, opts.extra_deny);
    emit_gpg_signing_rules(&mut sb, &home, opts.allow_gpg_signing, opts.extra_deny);
    emit_network_rules(
        &mut sb,
        opts.extra_ports,
        opts.allow_localhost_any,
        opts.proxy_port,
        opts.localhost_ports,
    );

    sb
}

// ── Profile section helpers ────────────────────────────────────
//
// Each function writes a contiguous SBPL block to the output string.
// Call order matters: SBPL uses last-match-wins, so denies must come
// after their corresponding allows. Do NOT reorder these calls.

fn emit_header(sb: &mut String, project: &str) {
    writeln!(sb, ";; Auto-generated by cplt").unwrap();
    writeln!(sb, ";; Project: {project}").unwrap();
    writeln!(sb, "(version 1)").unwrap();
    writeln!(sb, "(deny default)").unwrap();
    writeln!(sb).unwrap();

    writeln!(sb, "(import \"/System/Library/Sandbox/Profiles/bsd.sb\")").unwrap();
    writeln!(sb).unwrap();
}

fn emit_process_rules(sb: &mut String) {
    writeln!(sb, ";; Process execution").unwrap();
    writeln!(sb, "(allow process-exec)").unwrap();
    writeln!(sb, "(allow process-fork)").unwrap();
    // Allow sending signals to processes in the same sandbox (e.g. Turbopack killing workers)
    writeln!(sb, "(allow signal (target same-sandbox))").unwrap();
    writeln!(sb).unwrap();

    // TTY/terminal control — needed for interactive CLIs (e.g. Node.js setRawMode)
    writeln!(
        sb,
        ";; TTY control (ioctl for terminal raw mode, window size)"
    )
    .unwrap();
    writeln!(sb, "(allow file-ioctl)").unwrap();
    writeln!(sb).unwrap();

    // Device access — Node.js needs /dev/tty, /dev/null, /dev/urandom etc.
    writeln!(sb, ";; Device access (/dev/tty, /dev/null, /dev/urandom)").unwrap();
    writeln!(sb, "(allow file-read* (subpath \"/dev\"))").unwrap();
    writeln!(sb, "(allow file-write* (subpath \"/dev\"))").unwrap();
    writeln!(sb).unwrap();
}

fn emit_project_access(sb: &mut String, project: &str, allow_env_files: bool) {
    // Project directory — full access
    // file-map-executable needed for native Node addons in node_modules
    // (e.g. @next/swc-*, sharp, better-sqlite3 loaded via dlopen)
    writeln!(sb, ";; Project directory — full read/write").unwrap();
    writeln!(sb, "(allow file-read* (subpath \"{project}\"))").unwrap();
    writeln!(sb, "(allow file-write* (subpath \"{project}\"))").unwrap();
    writeln!(sb, "(allow file-map-executable (subpath \"{project}\"))").unwrap();
    writeln!(sb).unwrap();

    // Git persistence prevention — deny writes to files that execute outside the sandbox.
    // .git/hooks/ — post-checkout, pre-push etc. run outside sandbox on next git operation
    // .git/config — core.hooksPath can redirect hooks to /tmp, bypassing the hooks deny;
    //               url.*.insteadOf can hijack git remotes; include.path loads arbitrary config
    // .gitmodules — submodule URLs are a supply chain vector (git submodule update clones them)
    // These denies are more specific than the project allow, so they win (SBPL specificity).
    writeln!(sb, ";; Git persistence prevention").unwrap();
    writeln!(sb, "(deny file-write* (subpath \"{project}/.git/hooks\"))").unwrap();
    writeln!(sb, "(deny file-write* (literal \"{project}/.git/config\"))").unwrap();
    writeln!(sb, "(deny file-write* (literal \"{project}/.gitmodules\"))").unwrap();
    writeln!(sb).unwrap();

    // Sensitive project files — deny read of .env*, .pem, .key etc.
    // These often contain secrets that could be exfiltrated via HTTPS.
    // Placed after the project allow so deny wins (more specific filter).
    // Copilot can still write these files (creating .env from .env.example).
    if !allow_env_files {
        writeln!(sb, ";; Sensitive project files — deny read (.env*, keys)").unwrap();
        for pattern in SENSITIVE_PROJECT_PATTERNS {
            // SBPL regex matches against the full path, so we anchor to
            // any directory separator to avoid matching path components.
            writeln!(sb, "(deny file-read* (regex #\"/{pattern}\"))").unwrap();
        }
        writeln!(sb).unwrap();
    }
}

fn emit_home_access(sb: &mut String, home: &str) {
    // Copilot config — the CLI needs its auth tokens and settings.
    // file-map-executable is needed for native Node.js addons (keytar.node, pty.node, computer.node)
    // which are loaded via dlopen() from ~/.copilot/pkg/universal/*/prebuilds/
    writeln!(sb, ";; Copilot config + native modules").unwrap();
    writeln!(sb, "(allow file-read* (subpath \"{home}/.copilot\"))").unwrap();
    writeln!(sb, "(allow file-write* (subpath \"{home}/.copilot\"))").unwrap();
    writeln!(
        sb,
        "(allow file-map-executable (subpath \"{home}/.copilot\"))"
    )
    .unwrap();
    // Deny writes to Copilot's installed packages (native modules).
    // Prevents persistence: a rogue agent could replace keytar.node with a
    // malicious version that runs unsandboxed next time Copilot is launched.
    // Must come after the allow (last-match-wins).
    writeln!(sb, "(deny file-write* (subpath \"{home}/.copilot/pkg\"))").unwrap();
    writeln!(sb).unwrap();

    // GitHub CLI auth — Copilot spawns `gh auth token` which reads these specific files.
    // Only the auth files, not the entire ~/.config/gh directory.
    writeln!(sb, ";; GitHub CLI auth (specific files only)").unwrap();
    writeln!(
        sb,
        "(allow file-read* (literal \"{home}/.config/gh/hosts.yml\"))"
    )
    .unwrap();
    writeln!(
        sb,
        "(allow file-read* (literal \"{home}/.config/gh/config.yml\"))"
    )
    .unwrap();
    writeln!(sb).unwrap();

    // mise config — tool version manager reads global config for tool paths and settings.
    // Contains tool versions and PATH entries, no secrets.
    writeln!(sb, ";; mise config (tool versions, no secrets)").unwrap();
    writeln!(sb, "(allow file-read* (subpath \"{home}/.config/mise\"))").unwrap();
    writeln!(sb).unwrap();

    // Microsoft DeviceID — telemetry device identifier
    writeln!(sb, ";; Microsoft DeviceID").unwrap();
    writeln!(
        sb,
        "(allow file-read* (subpath \"{home}/Library/Application Support/Microsoft\"))"
    )
    .unwrap();
    writeln!(sb).unwrap();

    // macOS Keychain access — Copilot stores auth tokens here
    // Security framework needs read+write (locks the db file during access)
    writeln!(sb, ";; macOS Keychain (Copilot auth tokens)").unwrap();
    writeln!(
        sb,
        "(allow file-read* (subpath \"{home}/Library/Keychains\"))"
    )
    .unwrap();
    writeln!(
        sb,
        "(allow file-write* (subpath \"{home}/Library/Keychains\"))"
    )
    .unwrap();
    writeln!(sb).unwrap();
}

fn emit_system_access(sb: &mut String, home: &str) {
    // Mach IPC — Node.js and macOS frameworks need service lookups
    // (Keychain, security framework, DNS, system services)
    writeln!(sb, ";; Mach IPC (required for Node.js, Keychain, DNS)").unwrap();
    writeln!(sb, "(allow mach-lookup)").unwrap();
    writeln!(sb).unwrap();

    // System info — Node.js queries CPU count, memory, OS version
    writeln!(sb, ";; System info (Node.js runtime needs these)").unwrap();
    writeln!(sb, "(allow sysctl-read)").unwrap();
    writeln!(sb, "(allow ipc-posix-shm-read-data)").unwrap();
    writeln!(sb, "(allow ipc-posix-shm-write-data)").unwrap();
    writeln!(sb, "(allow ipc-posix-shm-write-create)").unwrap();
    writeln!(sb).unwrap();

    // User preferences — Keychain and security framework read preferences
    writeln!(sb, ";; User preferences (Keychain, security framework)").unwrap();
    writeln!(sb, "(allow user-preference-read)").unwrap();
    writeln!(sb).unwrap();

    // Security framework databases — needed for Keychain/TLS operations
    writeln!(sb, ";; Security framework databases").unwrap();
    writeln!(sb, "(allow file-read* (subpath \"/private/var/db/mds\"))").unwrap();
    writeln!(sb).unwrap();

    // Git config (read-only)
    writeln!(sb, ";; Git config (read-only)").unwrap();
    writeln!(sb, "(allow file-read* (literal \"{home}/.gitconfig\"))").unwrap();
    writeln!(
        sb,
        "(allow file-read* (literal \"{home}/.config/git/config\"))"
    )
    .unwrap();
    writeln!(sb).unwrap();

    // Tool version files — mise/asdf read these to determine tool versions
    writeln!(sb, ";; Tool version files (mise/asdf, read-only)").unwrap();
    writeln!(sb, "(allow file-read* (literal \"{home}/.tool-versions\"))").unwrap();
    writeln!(sb).unwrap();
}

/// Allow reading global git hooks from `core.hooksPath`.
///
/// Git hooks are user-configured scripts that run on commit/push/etc.
/// We explicitly deny writes to prevent a persistence attack: a rogue agent
/// could plant hooks (pre-commit, post-checkout) that execute unsandboxed
/// the next time the user runs git outside cplt.
fn emit_git_hooks(sb: &mut String, git_hooks_path: Option<&Path>) {
    if let Some(hooks) = git_hooks_path {
        let p = hooks.to_string_lossy();
        writeln!(sb, ";; Global git hooks (core.hooksPath)").unwrap();
        writeln!(sb, "(allow file-read* (subpath \"{p}\"))").unwrap();
        // Deny writes — hooks must not be modifiable from the sandbox.
        // Must come after any broader allow (last-match-wins).
        writeln!(sb, "(deny file-write* (subpath \"{p}\"))").unwrap();
        writeln!(sb).unwrap();
    }
}

fn emit_tool_dirs(sb: &mut String, home: &str, existing_home_tool_dirs: Option<&[String]>) {
    writeln!(sb, ";; Developer tools").unwrap();
    for dir in TOOL_READ_DIRS {
        writeln!(sb, "(allow file-read* (subpath \"{dir}\"))").unwrap();
        writeln!(sb, "(allow file-map-executable (subpath \"{dir}\"))").unwrap();
    }
    // Home tool dirs: use discovered existing dirs if available, else include all
    let active_dirs: Vec<&HomeToolDir> = match existing_home_tool_dirs {
        Some(dirs) => HOME_TOOL_DIRS
            .iter()
            .filter(|d| dirs.iter().any(|s| s == d.path))
            .collect(),
        None => HOME_TOOL_DIRS.iter().collect(),
    };
    for dir in &active_dirs {
        let p = dir.path;
        writeln!(sb, "(allow file-read* (subpath \"{home}/{p}\"))").unwrap();
        if dir.process_exec {
            writeln!(sb, "(allow process-exec (subpath \"{home}/{p}\"))").unwrap();
        }
        if dir.map_exec {
            writeln!(sb, "(allow file-map-executable (subpath \"{home}/{p}\"))").unwrap();
        }
        if dir.write {
            writeln!(sb, "(allow file-write* (subpath \"{home}/{p}\"))").unwrap();
        }
    }
    // Deny exec from writable dirs that should not have it.
    // Must come AFTER allows (last-match-wins in Seatbelt).
    // The blanket (allow process-exec) means we need explicit denies,
    // not just absence of a per-dir allow.
    for dir in &active_dirs {
        let p = dir.path;
        if dir.write && !dir.process_exec {
            writeln!(sb, "(deny process-exec (subpath \"{home}/{p}\"))").unwrap();
        }
        if dir.write && !dir.map_exec {
            writeln!(sb, "(deny file-map-executable (subpath \"{home}/{p}\"))").unwrap();
        }
    }

    // Deny non-dev cache dirs under ~/Library/Caches/ (browsers, system apps).
    // Uses prefix matching on reverse-domain bundle IDs — stable across versions.
    // Dev tool caches (go-build, pip, etc.) don't use these prefixes, so they
    // pass through automatically without needing an explicit allowlist.
    // Xcode dev tools (com.apple.dt.*) are re-allowed after the broad com.apple. deny.
    writeln!(sb, ";; Non-dev cache dirs denied (browsers, system apps)").unwrap();
    for prefix in DENIED_CACHE_PREFIXES {
        // Escape dots for SBPL regex
        let escaped = prefix.replace('.', r"\.");
        writeln!(
            sb,
            "(deny file-read* (regex #\"^{home}/Library/Caches/{escaped}\"))"
        )
        .unwrap();
        writeln!(
            sb,
            "(deny file-write* (regex #\"^{home}/Library/Caches/{escaped}\"))"
        )
        .unwrap();
    }
    // Re-allow Xcode dev tools (com.apple.dt.Xcode, com.apple.dt.xcodebuild)
    writeln!(
        sb,
        "(allow file-read* (regex #\"^{home}/Library/Caches/com\\.apple\\.dt\\.\"))"
    )
    .unwrap();
    writeln!(
        sb,
        "(allow file-write* (regex #\"^{home}/Library/Caches/com\\.apple\\.dt\\.\"))"
    )
    .unwrap();

    // Copilot CLI v1.0.22+ stores native modules and helper binaries in
    // ~/Library/Caches/copilot/pkg/. The Library/Caches deny above blocks
    // process-exec and file-map-executable broadly. These carve-outs re-enable:
    //   - file-map-executable: dlopen() for native modules (keytar.node, pty.node)
    //   - process-exec: helper binaries (spawn-helper, rg) that Copilot spawns
    //   - deny file-write*: prevent write-then-exec attacks (writable + executable
    //     is a binary-drop staging risk). Auto-update is already blocked inside
    //     the sandbox (--no-auto-update), so writes are not needed.
    // Must come AFTER the denies (last-match-wins in SBPL).
    writeln!(
        sb,
        "(allow file-map-executable (subpath \"{home}/Library/Caches/copilot/pkg\"))"
    )
    .unwrap();
    writeln!(
        sb,
        "(allow process-exec (subpath \"{home}/Library/Caches/copilot/pkg\"))"
    )
    .unwrap();
    writeln!(
        sb,
        "(deny file-write* (subpath \"{home}/Library/Caches/copilot/pkg\"))"
    )
    .unwrap();
    writeln!(sb).unwrap();
}

/// Allow reading and dlopen from the Copilot CLI package directory.
/// Needed when Copilot is installed via a non-standard Node version manager
/// (e.g. `n` at ~/n/) whose path isn't covered by TOOL_READ_DIRS.
fn emit_copilot_install(sb: &mut String, install_dir: Option<&Path>) {
    if let Some(dir) = install_dir {
        let p = dir.to_string_lossy();
        writeln!(sb, ";; Copilot CLI installation directory").unwrap();
        writeln!(sb, "(allow file-read* (subpath \"{p}\"))").unwrap();
        writeln!(sb, "(allow file-map-executable (subpath \"{p}\"))").unwrap();
        writeln!(sb).unwrap();
    }
}

fn emit_system_files(sb: &mut String) {
    writeln!(sb, ";; System config (specific files)").unwrap();
    for path in SYSTEM_READ_FILES {
        if path.contains('/') && !path.ends_with('/') {
            // Could be a file or directory — use subpath for dirs like /private/etc/ssl
            if path.ends_with("ssl") {
                writeln!(sb, "(allow file-read* (subpath \"{path}\"))").unwrap();
            } else {
                writeln!(sb, "(allow file-read* (literal \"{path}\"))").unwrap();
            }
        } else {
            writeln!(sb, "(allow file-read* (literal \"{path}\"))").unwrap();
        }
    }
    writeln!(sb).unwrap();
}

fn emit_temp_rules(sb: &mut String, allow_tmp_exec: bool, scratch_dir: Option<&Path>) {
    writeln!(sb, ";; Temp directories").unwrap();
    writeln!(sb, "(allow file-read* (subpath \"/private/tmp\"))").unwrap();
    writeln!(sb, "(allow file-write* (subpath \"/private/tmp\"))").unwrap();
    writeln!(sb, "(allow file-read* (subpath \"/private/var/folders\"))").unwrap();
    writeln!(sb, "(allow file-write* (subpath \"/private/var/folders\"))").unwrap();
    if !allow_tmp_exec {
        // Deny direct execution and dlopen from writable temp dirs.
        // Prevents write-then-exec attacks (drop binary → execute it).
        // Limitation: does NOT block interpreter-based exec (e.g. `bash /tmp/evil.sh`,
        // `node /tmp/evil.js`) because the exec target is the interpreter, not the script.
        writeln!(sb, "(deny process-exec (subpath \"/private/tmp\"))").unwrap();
        writeln!(sb, "(deny file-map-executable (subpath \"/private/tmp\"))").unwrap();
        writeln!(sb, "(deny process-exec (subpath \"/private/var/folders\"))").unwrap();
        writeln!(
            sb,
            "(deny file-map-executable (subpath \"/private/var/folders\"))"
        )
        .unwrap();
    }
    writeln!(sb).unwrap();

    // Per-session scratch directory — write+exec for tools that compile-then-execute
    if let Some(scratch) = scratch_dir {
        let scratch_path = scratch.to_string_lossy();
        writeln!(sb, ";; Per-session scratch directory (TMPDIR redirect)").unwrap();
        writeln!(sb, "(allow file-read* (subpath \"{scratch_path}\"))").unwrap();
        writeln!(sb, "(allow file-write* (subpath \"{scratch_path}\"))").unwrap();
        writeln!(sb, "(allow process-exec (subpath \"{scratch_path}\"))").unwrap();
        writeln!(
            sb,
            "(allow file-map-executable (subpath \"{scratch_path}\"))"
        )
        .unwrap();
        writeln!(sb).unwrap();
    }
}

fn emit_user_allows(sb: &mut String, extra_read: &[PathBuf], extra_write: &[PathBuf]) {
    if !extra_read.is_empty() || !extra_write.is_empty() {
        writeln!(sb, ";; User-specified allows").unwrap();
        for path in extra_read {
            let p = path.to_string_lossy();
            writeln!(sb, "(allow file-read* (subpath \"{p}\"))").unwrap();
        }
        for path in extra_write {
            let p = path.to_string_lossy();
            writeln!(sb, "(allow file-read* (subpath \"{p}\"))").unwrap();
            writeln!(sb, "(allow file-write* (subpath \"{p}\"))").unwrap();
        }
        writeln!(sb).unwrap();
    }
}

fn emit_deny_rules(sb: &mut String, home: &str, extra_deny: &[PathBuf]) {
    // Sensitive directories — DENY (after allows, so these override)
    writeln!(sb, ";; Sensitive directories — DENIED").unwrap();
    for dotfile in DENIED_DOTFILES {
        writeln!(sb, "(deny file-read* (subpath \"{home}/{dotfile}\"))").unwrap();
        writeln!(sb, "(deny file-write* (subpath \"{home}/{dotfile}\"))").unwrap();
    }
    for file in DENIED_FILES {
        writeln!(sb, "(deny file-read* (literal \"{home}/{file}\"))").unwrap();
        writeln!(sb, "(deny file-write* (literal \"{home}/{file}\"))").unwrap();
    }
    for path in extra_deny {
        let p = path.to_string_lossy();
        writeln!(sb, "(deny file-read* (subpath \"{p}\"))").unwrap();
        writeln!(sb, "(deny file-write* (subpath \"{p}\"))").unwrap();
    }
    writeln!(sb).unwrap();
}

/// Allow GPG commit signing when `--allow-gpg-signing` is set.
///
/// Emitted AFTER `emit_deny_rules` (which denies all of `~/.gnupg`).
/// SBPL uses last-match-wins, so these targeted allows override the
/// blanket deny. Private keys (`private-keys-v1.d/` and legacy
/// `secring.gpg`) are explicitly re-denied after the allows to
/// ensure they remain locked.
///
/// If any `extra_deny` path overlaps with `~/.gnupg`, GPG rules are
/// skipped entirely — explicit user denies always win.
fn emit_gpg_signing_rules(
    sb: &mut String,
    home: &str,
    allow_gpg_signing: bool,
    extra_deny: &[PathBuf],
) {
    if !allow_gpg_signing {
        return;
    }
    // Explicit --deny-path wins: if the user denied anything under ~/.gnupg,
    // skip all GPG allows so the deny is not overridden.
    let gnupg_dir = format!("{home}/.gnupg");
    for deny in extra_deny {
        let d = deny.to_string_lossy();
        if d == gnupg_dir || d.starts_with(&format!("{gnupg_dir}/")) {
            writeln!(
                sb,
                ";; GPG signing skipped: --deny-path overlaps with ~/.gnupg"
            )
            .unwrap();
            return;
        }
    }
    writeln!(sb, ";; GPG signing (--allow-gpg-signing)").unwrap();
    // Allow read-only access to public keyring and config
    for file in GPG_SIGNING_ALLOW_FILES {
        writeln!(sb, "(allow file-read* (literal \"{home}/.gnupg/{file}\"))").unwrap();
    }
    // Allow connecting to the GPG agent socket for signing requests.
    // The agent holds private keys in memory — the socket is the only
    // interface, and the Assuan protocol cannot export keys.
    // file-read* is needed for the inode lookup before connect(2).
    // S.keyboxd is needed for GnuPG 2.4+ with keyboxd-managed public keys.
    for socket in &["S.gpg-agent", "S.keyboxd"] {
        writeln!(
            sb,
            "(allow file-read* (literal \"{home}/.gnupg/{socket}\"))"
        )
        .unwrap();
        writeln!(
            sb,
            "(allow network-outbound (literal \"{home}/.gnupg/{socket}\"))"
        )
        .unwrap();
    }
    // Private keys must remain denied even with GPG signing enabled.
    // Covers both modern (private-keys-v1.d/) and legacy (secring.gpg).
    writeln!(
        sb,
        "(deny file-read* (subpath \"{home}/.gnupg/private-keys-v1.d\"))"
    )
    .unwrap();
    writeln!(
        sb,
        "(deny file-read* (literal \"{home}/.gnupg/secring.gpg\"))"
    )
    .unwrap();
    // No write access to any part of .gnupg
    writeln!(sb, "(deny file-write* (subpath \"{home}/.gnupg\"))").unwrap();
    writeln!(sb).unwrap();
}

fn emit_network_rules(
    sb: &mut String,
    extra_ports: &[u16],
    allow_localhost_any: bool,
    proxy_port: Option<u16>,
    localhost_ports: &[u16],
) {
    // Network — outbound restricted to HTTPS/HTTP, localhost blocked by default.
    // Copilot CLI connects directly to api.githubcopilot.com:443 etc.
    // We can't do domain-based rules in SBPL, but we can restrict ports and
    // block localhost to prevent SSRF attacks against local services.
    writeln!(sb, ";; Network — restricted outbound, localhost blocked").unwrap();

    // DNS resolution — only the specific mDNSResponder socket, NOT all unix-sockets.
    // Blocking (remote unix-socket) prevents SSH agent access via launchd sockets.
    writeln!(
        sb,
        "(allow network-outbound (literal \"/private/var/run/mDNSResponder\"))"
    )
    .unwrap();

    // Outbound TCP restricted to port 443 (HTTPS only).
    // All Copilot/GitHub APIs use HTTPS — port 80 is not needed and would
    // allow unencrypted exfiltration. Use --allow-port 80 if required.
    writeln!(sb, "(deny network-outbound (remote tcp))").unwrap();
    writeln!(sb, "(allow network-outbound (remote ip \"*:443\"))").unwrap();

    // Extra ports (e.g., MCP servers, custom services)
    for port in extra_ports {
        writeln!(sb, "(allow network-outbound (remote ip \"*:{port}\"))").unwrap();
    }

    // Block localhost outbound — prevents SSRF to local dev servers, databases, etc.
    // Must come AFTER port allows so it overrides them for localhost.
    if !allow_localhost_any {
        writeln!(sb, "(deny network-outbound (remote ip \"localhost:*\"))").unwrap();
    } else {
        // Explicitly allow all localhost ports — the general TCP deny above
        // blocks non-443 ports, so we need a specific allow for localhost.
        writeln!(sb, "(allow network-outbound (remote ip \"localhost:*\"))").unwrap();
    }

    // Carve-outs for specific localhost ports (proxy, MCP servers, dev servers).
    // These come AFTER the deny so they override it (last-match-wins in SBPL).
    if let Some(port) = proxy_port {
        writeln!(
            sb,
            "(allow network-outbound (remote ip \"localhost:{port}\"))"
        )
        .unwrap();
    }
    for port in localhost_ports {
        writeln!(
            sb,
            "(allow network-outbound (remote ip \"localhost:{port}\"))"
        )
        .unwrap();
    }

    // Allow inbound for localhost services (proxy listener, MCP servers).
    // This only allows accepting connections, not initiating them.
    writeln!(sb, "(allow network-inbound (local tcp))").unwrap();
}
